export const attendees = [
  { id: '00', name: '--', plusOne: false, twoRSVP: false },
  { id: '01', name: 'Andrea Bougiouklis', plusOne: true, twoRSVP: false },
  { id: '02', name: 'Bryan Molyneaux & Myranda Ruel', plusOne: false, twoRSVP: true },
  { id: '03', name: 'Carl Molyneaux & Brittney Closs', plusOne: false, twoRSVP: true },
  { id: '04', name: 'Dakotah Molyneaux', plusOne: true, twoRSVP: false },
  { id: '05', name: 'Darius Jones', plusOne: true, twoRSVP: false },
  { id: '06', name: 'Deborah Foley & Patrick Foley', plusOne: false, twoRSVP: true },
  { id: '07', name: 'Erica Edwards', plusOne: true, twoRSVP: false },
  { id: '08', name: 'Hayden McKnight', plusOne: true, twoRSVP: false },
  { id: '09', name: 'Janet Basaraba', plusOne: true, twoRSVP: false },
  { id: '10', name: 'Josh Armstrong', plusOne: true, twoRSVP: false },
  { id: '11', name: 'Justin Basaraba & Veronica Arruda', plusOne: true, twoRSVP: false },
  { id: '12', name: 'Katelyn Basaraba & Tracy Basaraba', plusOne: false, twoRSVP: true },
  { id: '13', name: 'Katherine Basaraba & John Banos', plusOne: false, twoRSVP: true },
  { id: '14', name: 'Kennedy Basaraba-Hoyte', plusOne: true, twoRSVP: false },
  { id: '15', name: 'Patrick Kye Foley & Camille Daoust', plusOne: false, twoRSVP: true },
  { id: '16', name: 'Rebecca Molyneaux & Kevin Choffe', plusOne: false, twoRSVP: true },
  { id: '17', name: 'Stephanie Winter & Richard Winter', plusOne: false, twoRSVP: true },
  { id: '18', name: 'Trishauna Hyatt', plusOne: true, twoRSVP: false },
  { id: '19', name: 'Tyler Street', plusOne: true, twoRSVP: false },
  { id: '20', name: 'Victoria Kalonomos & Andrew Kozaris', plusOne: false, twoRSVP: true },
  { id: '21', name: 'Zack Cameron Hackett', plusOne: false, twoRSVP: false },
  { id: '22', name: 'Zach McCracken', plusOne: true, twoRSVP: false }
];
